### ISSUE TITLE
getTAITime() does not return colon separate string

### ISSUE THREAD

**Issue by kaviyaankhalil** [RiedelCommunications/test-nmos-is0405#1]
https://github.com/RiedelCommunications/test-nmos-is0405/blob/27d11d31b035ff0b9b411aab2f2a5319e52af1a4/IS0501Test.py#L1479

Requesting absolute activation using a TAI time generated with this function results in (hopefully) an HTTP Error 400 due to malformed request, because the requested_time never gets colon separated as required by the spec:

https://github.com/AMWA-TV/nmos-device-connection-management/blob/5c6fb373e9d222259e2b51376f01a74e697c0b2a/APIs/schemas/v1.0-activation-schema.json#L32

**Comment by jasperpeeters** [comment]
Thanks for pointing out. This was fixed by [fba23e2468d71f72ed6f2b69eccf12ecf66f0383](https://github.com/RiedelCommunications/test-nmos-is0405/commit/4d74d628c3758907476598455f46a2f715ea70e9)
