### ISSUE TITLE
Time waited here may not be sufficient for some devices.

### ISSUE THREAD

**Issue by kaviyaankhalil** [RiedelCommunications/test-nmos-is0405#2]
https://github.com/RiedelCommunications/test-nmos-is0405/blob/27d11d31b035ff0b9b411aab2f2a5319e52af1a4/IS0501Test.py#L1105

Does the AMWA spec have anything to say about the amount of time that may pass between the scheduled activation time and the actual completion of activation (device actually finishes activation configuration and moves staged parameters to the /active endpoint)?  

Perhaps it would be possible to poll this value a couple times to allow slower devices sufficient time to activate.

**Comment by jasperpeeters** [comment]
Thanks for pointing this out @kaviyaankhalil 
I'm not aware of any detailed specification of the required time between the scheduling and actual completion of an activation. So for now the test will wait "a bit" if it doesn't detect the required change and will retry. In that case the user will be notified about this on the results page. If retry >= 3 the test will fail nevertheless. Possibly we have to change the amount of time to wait later on.
