### ISSUE TITLE
generate_destination_ports could accept other constraints

### ISSUE THREAD

**Issue by garethsb** [RiedelCommunications/test-nmos-is0405#3]
generate_destination_ports at https://github.com/RiedelCommunications/test-nmos-is0405/blob/master/IS0501Test.py#L1259 only looks for minimum and maximum values, but it could work with e.g. an enum constraint also.
(Originally raised as https://github.com/bbc/nmos-cm-automated-testing/issues/1)

**Comment by jasperpeeters** [comment]
Thanks for pointing this out @garethsb-sony .
This is now fixed in https://github.com/RiedelCommunications/test-nmos-is0405/commit/0198cee168ce4815a4d311591c0b757a31063042
