### ISSUE TITLE
RefResolver opens locations incorrectly on Linux

### ISSUE THREAD

**Issue by andrewbonney** [RiedelCommunications/test-nmos-is0405#5]
I'm assuming this is a Linux vs Windows issue. The RefResolver lines using 'file:///' cause an exception on Linux. Looking at an example online this seems to be resolvable by either using 'file://' or a snippet like the following:

```
if os.name == 'nt':
    FILE_PREFIX = 'file:///'
else:
    FILE_PREFIX = 'file:'
```

Provided file:// does work on Windows that might be simplest, but I can't test that immediately here.

**Comment by jasperpeeters** [comment]
Thanks for pointing this out @andrewbonney
